In [1]:
import torch

In [3]:
x = torch.rand(3,requires_grad=True)
x

tensor([0.6300, 0.5488, 0.2568], requires_grad=True)

In [4]:
y = x+2
print(x)
print(y)

tensor([0.6300, 0.5488, 0.2568], requires_grad=True)
tensor([2.6300, 2.5488, 2.2568], grad_fn=<AddBackward0>)


In [10]:
z = y*y*2
print(z)

tensor([13.8335, 12.9932, 10.1863], grad_fn=<MulBackward0>)


In [13]:
# z = z.mean()
v = torch.tensor([0.1,1.0,0.01],dtype=torch.float32)
z

tensor([13.8335, 12.9932, 10.1863], grad_fn=<MulBackward0>)

In [14]:
z.backward(v)

In [15]:
print(x.grad)

tensor([ 4.5586, 13.5938,  3.0993])


In [18]:
weights = torch.ones(4,requires_grad=True)
for epoch in range(5):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
tensor([12., 12., 12., 12.])
tensor([15., 15., 15., 15.])
