In [8]:
!pip install torch


[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import torch

In [16]:
x = torch.empty(3)
x

tensor([0., 0., 0.])

In [17]:
y = torch.empty(3,5)
y

tensor([[1.8007e+21, 6.7963e-43, 1.8004e+21, 6.7963e-43, 1.8003e+21],
        [6.7963e-43, 1.8004e+21, 6.7963e-43, 1.8423e+21, 6.7963e-43],
        [1.8421e+21, 6.7963e-43, 1.8421e+21, 6.7963e-43, 1.8421e+21]])

In [18]:
x = torch.ones(2,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
x = torch.tensor([1,2,3,4,6,7])
x

tensor([1, 2, 3, 4, 6, 7])

#### Basic Operations

In [24]:
x = torch.rand(2,3)
y = torch.rand(2,3)
z = x+y #or z = torch.add(x,y)
print(x)
print(y)
print(z)

tensor([[0.2379, 0.9146, 0.4730],
        [0.1273, 0.9143, 0.2898]])
tensor([[0.2706, 0.2447, 0.8236],
        [0.7999, 0.1657, 0.0043]])
tensor([[0.5085, 1.1593, 1.2966],
        [0.9272, 1.0800, 0.2940]])


In [25]:
#inplace addition
y.add_(x)
print(y)

tensor([[0.5085, 1.1593, 1.2966],
        [0.9272, 1.0800, 0.2940]])


In [26]:
a = x-y
b = x*y
c = x/y
print(a)
print(b)
print(c)

tensor([[-0.2706, -0.2447, -0.8236],
        [-0.7999, -0.1657, -0.0043]])
tensor([[0.1210, 1.0604, 0.6133],
        [0.1180, 0.9874, 0.0852]])
tensor([[0.4678, 0.7889, 0.3648],
        [0.1373, 0.8466, 0.9854]])


In [37]:
#slicing
x = torch.rand(5,3)
print(x)
print(x[1])
print(x[2,2].item())

tensor([[0.9511, 0.6269, 0.4186],
        [0.8746, 0.1322, 0.1999],
        [0.0509, 0.9210, 0.0730],
        [0.2980, 0.6208, 0.5359],
        [0.3079, 0.9241, 0.4937]])
tensor([0.8746, 0.1322, 0.1999])
0.07300466299057007


In [38]:
#1d vector
y = x.view(15)
y

tensor([0.9511, 0.6269, 0.4186, 0.8746, 0.1322, 0.1999, 0.0509, 0.9210, 0.0730,
        0.2980, 0.6208, 0.5359, 0.3079, 0.9241, 0.4937])

In [42]:
#converting numpy to torch tensor
import numpy as np
a = torch.ones(5)
b = a.numpy()
print(type(a))
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [44]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
a+=1
b

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


tensor([2., 2., 2., 2., 2.], dtype=torch.float64)